services:
  - type: web
    name: envirosense-backend
    env: python
    buildCommand: pip install -r requirements.txt && python apply_migration.py
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: POSTGRES_HOST
        fromDatabase:
          name: envirosense-db
          property: host
      - key: POSTGRES_DB
        fromDatabase:
          name: envirosense-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: envirosense-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: envirosense-db
          property: password
      - key: POSTGRES_PORT
        fromDatabase:
          name: envirosense-db
          property: port

databases:
  - name: envirosense-db
    plan: free
