[build]
  base = "web"
  publish = "build"
  command = "CI=false npm run build"

# Handle SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
